### ISSUE TITLE
Consider user's timezone when sending notifications

### ISSUE THREAD

**Issue by jedrzej** [x-team/unleash-slack-bot#13]
When time left is calculated and notifications are sent, server time is used. Slackbot fetches list of Slack users from SlackAPI and the response contains information about users timezone offset. This could be used to calculate time left in given user's timezone.

**Comment by jedrzej** [comment]
@karolsojko please confirm that this task makese sense, I'll be happy to work on that :)

**Comment by karolsojko** [comment]
@jedrzej looks good for me - @theanxy what do you say ?

**Comment by theanxy** [comment]
Sure, that’d be nice to have!

**Comment by jedrzej** [comment]
https://github.com/x-team/unleash-slack-bot/pull/14
