### ISSUE TITLE
Weird notification from slackbot

### ISSUE THREAD

**Issue by jedrzej** [x-team/unleash-slack-bot#15]
![capture 2016-04-05 at 9 52 04](https://cloud.githubusercontent.com/assets/291904/14202715/d6cd037a-f7f9-11e5-9e12-ff28d67b8686.png)

Today I got a weird notification from slackbot. It mentiones my goal, which is correct, but then it also mentiones someone else's goal.

**Comment by jedrzej** [comment]
It happened again today, I got someone else's Translator goal

**Comment by karolsojko** [comment]
Debugged it locally - seemed fine. Redeployed it on staging and prod without cache - will check again tomorrow if it occures again.
