### ISSUE TITLE
Implement events logging

### ISSUE THREAD

**Issue by theanxy** [x-team/unleash-slack-bot#2]
It would be good to log all events (messages sent by the bot), so that all communication related to the bot is transparent and we can easier pinpoint problems.

Potential integration: https://rollbar.com/

**Comment by theanxy** [comment]
Thanks, that looks good. However I was thinking about logging successfully triggered events as well, so that we can debug all messages being sent from the bot, especially direct messages.

Looking at https://rollbar.com/pricing/, that should still be fine in the free plan

**Comment by karolsojko** [comment]
on it :+1:
