### ISSUE TITLE
Notifications about "your goal is overdue" are not sent anymore

### ISSUE THREAD

**Issue by jedrzej** [x-team/unleash-slack-bot#25]

**Comment by karolsojko** [comment]
@jkbdbrnwsk @jedrzej please test on staging :)

**Comment by jkbdbrnwsk** [comment]
Seems it's working now, even every hour ;) https://www.dropbox.com/s/ghzdl5m29yk7qmr/Screenshot%202016-04-29%2014.04.18.png?dl=0

**Comment by karolsojko** [comment]
Should be fixed now @jkbdbrnwsk @jedrzej (probably will notify one last time ;))
